language: node_js

node_js:
  - "12"

cache:
  directories:
    - "node_modules"

stages:
  - setup
  - deploy

jobs:
  include:
    - stage: setup
      script:
        - npm i
    - stage: deploy
      deploy:
        provider: heroku
        api_key: "$HEROKU_API_KEY"
        app: "test-multiplayer-server"
        skip_cleanup: true
